FWDRAPUtils.onReady(function(){
   new FWDRAP({
    instanceName:"fwdrapPlayer0",
    parentId:"menu-m",
    playlistsId:"fwdrapMainPlaylist0",
    mainFolderPath:"https://www.webdesign-flash.ro/p/rap/content/",
    skinPath:"minimal_skin_dark",
					showSoundCloudUserNameInTitle:"yes",
					googleAnalyticsTrackingCode:"",
					useDeepLinking:"yes",
					useYoutube:"yes",
					youtubeAPIKey:"AIzaSyBQlBGEPaAq_UEgcxQ-wX9utp96_bD2dHU",
					useVideo:"yes",
					rightClickContextMenu:"default",
					showButtonsToolTips:"yes",
					initializeOnlyWhenVisible:"no",
					addKeyboardSupport:"yes",
					useContinuousPlayback:'no',
					autoPlay:"no",
					loop:"no",
					shuffle:"no",
					useVectorIcons:"no",
					useHEXColorsForSkin:"no",
					privatePassword:"428c841430ea18a70f7b06525d4b748a",
					soundCloudAPIKey:"r4wruADPCq7iqJomagvYpdehvILa2bgE",
					normalHEXButtonsColor:"#FF0000",
					normalHEXButtonsColor2:"#00FF00",
					maxWidth:801,
					volume:.9,
					toolTipsButtonsHideDelay:1.5,
					toolTipsButtonsBackgroundColor:"#FFFFFF",
					toolTipsButtonFontColor:"#5a5a5a",
					//controller settings
					animateOnIntro:"yes",
					showNextAndPrevButtons:"yes",
					showFullScreenButton:"yes",
					showThumbnail:"yes",
					showLoopButton:"yes",
					showShuffleButton:"yes",
					showDownloadMp3Button:"yes",
					showBuyButton:"yes",
					showShareButton:"yes",
					disableAudioScrubbar:"no",
					showMainScrubberAndVolumeScrubberToolTipLabel:"yes",
					expandBackground:"no",
					titleColor:"#FFFFFF",
					timeColor:"#888888",
					scrubbersToolTipLabelBackgroundColor:"#FFFFFF",
					scrubbersToolTipLabelFontColor:"#5a5a5a",
					//controller align and size settings (described in detail in the documentation!)
					controllerHeight:76,
					startSpaceBetweenButtons:9,
					spaceBetweenButtons:8,
					separatorOffsetOutSpace:5,
					separatorOffsetInSpace:9,
					lastButtonsOffsetTop:14,
					allButtonsOffsetTopAndBottom:14,
					titleBarOffsetTop:13,
					mainScrubberOffsetTop:47,
					spaceBetweenMainScrubberAndTime:10,
					startTimeSpace:10,
					scrubbersOffsetWidth:2,
					scrubbersOffestTotalWidth:0,
					volumeButtonAndScrubberOffsetTop:47,
					spaceBetweenVolumeButtonAndScrubber:6,
					volumeScrubberOffestWidth:4,
					scrubberOffsetBottom:10,
					equlizerOffsetLeft:1,
					//playlists window settings
					showPlaylistsSearchInput:"yes",
					usePlaylistsSelectBox:"yes",
					showPlaylistsSelectBoxNumbers:"yes",
					showPlaylistsButtonAndPlaylists:"yes",
					showPlaylistsByDefault:"no",
					randomizePlaylist:"no",
					playlistLoop:"yes",
					thumbnailSelectedType:"opacity",
					startAtPlaylist:0,
					startAtTrack:0,
					startAtRandomTrack:"no",
					buttonsMargins:15,
					thumbnailMaxWidth:350, 
					thumbnailMaxHeight:350,
					horizontalSpaceBetweenThumbnails:40,
					verticalSpaceBetweenThumbnails:40,
					playlistSelectorHeight: 37,
					mainSelectorBackgroundSelectedColor:"#FFFFFF",
					mainSelectorTextNormalColor:"#FFFFFF",
					mainSelectorTextSelectedColor:"#000000",
					mainButtonTextNormalColor:"#888888",
					mainButtonTextSelectedColor:"#FFFFFF",
					//playlist settings
					playTrackAfterPlaylistLoad:"no",
					showPlayListButtonAndPlaylist:"yes",
					showPlayListOnMobile:"yes",
					showPlayListByDefault:"yes",
					showPlaylistItemPlayButton:"yes",
					showPlaylistItemDownloadButton:"yes",
					showPlaylistItemBuyButton:"yes",
					forceDisableDownloadButtonForPodcast:"yes",
					forceDisableDownloadButtonForOfficialFM:"yes",
					forceDisableDownloadButtonForFolder:"yes",
					addScrollBarMouseWheelSupport:"yes",
					showTracksNumbers:"yes",
					playlistBackgroundColor:"#000000",
					trackTitleNormalColor:"#888888",
					trackTitleSelectedColor:"#FFFFFF",
					trackDurationColor:"#888888",
					playlistItemHeight: 33,
					maxPlaylistItems:40,
					nrOfVisiblePlaylistItems:10,
					trackTitleOffsetLeft:0,
					playPauseButtonOffsetLeftAndRight:11,
					durationOffsetRight:9,
					downloadButtonOffsetRight:11,
					scrollbarOffestWidth:7,
					//visualizer
					useVisualizer:'yes',
					visualizerRandomPreset:"yes",
					visualizerPreset:"wave1",
					visualizerColor:["#AAAAAA", "#999999", "#888888", "#777777", "#666666"],
					visualizerCapColor: "#FFFFFF",
					//playback rate / speed
					playbackRateButtonsMargins: 7,
					showPlaybackRateButton:"yes",
					defaultPlaybackRate:1, //min - 0.5 / max - 3
					playbackRateWindowTextColor:"#FFFFFF",
					//password window
					borderColor:"#333333",
					secondaryLabelsColor:"#a1a1a1",
					textColor:"#5a5a5a",
					inputBackgroundColor:"#000000",
					inputColor:"#FFFFFF",
					//search bar settings
					showSearchBar:"yes",
					showSortButtons:"yes",
					searchInputColor:"#999999",
					searchBarHeight:38,
					inputSearchTextOffsetTop:1,
					inputSearchOffsetLeft:0,
					//popup settings
					showPopupButton:"yes",
					openPopupOnPlay:"no",
					popupWindowBackgroundColor:"#878787",
					popupWindowWidth:790,
	           		popupWindowHeight:483,
					//a to b loop
					atbTimeTextColorNormal:"#888888",
					atbTimeTextColorSelected:"#FFFFFF",
					atbButtonTextNormalColor:"#888888",
					atbButtonTextSelectedColor:"#FFFFFF",
					atbButtonBackgroundNormalColor:"#FFFFFF",
					atbButtonBackgroundSelectedColor:"#000000",
					//login
					playIfLoggedIn:"no",
					playIfLoggedInMessage:"Please <a href='https://google.com' target='_blank'>login</a> to access this track."
				});
			}
