var page="demos";
			var gridId = 0;

			function setupDemoPlayer(){
				new FWDRAP({
					//main settings
					instanceName:"fwdrapPlayer0",
					parentId:"menu-m",
					playlistsId:"fwdrapMainPlaylist0",
					mainFolderPath:"https://www.webdesign-flash.ro/p/rap/content/",
					skinPath:"modern_skin_white",
					showSoundCloudUserNameInTitle:"yes",
					googleAnalyticsTrackingCode:"",
					proxyCors:"",
					useDeepLinking:"yes",
					useYoutube:"yes",
					youtubeAPIKey:"",
					useVideo:"yes",
					rightClickContextMenu:"default",
					showButtonsToolTips:"yes",
					initializeOnlyWhenVisible:"no",
					addKeyboardSupport:"yes",
					useContinuousPlayback:'no',
					autoPlay:"no",
					loop:"no",
					shuffle:"no",
					useVectorIcons:"yes",
					useHEXColorsForSkin:"no",
					privatePassword:"428c841430ea18a70f7b06525d4b748a",
					soundCloudAPIKey:"",
					normalHEXButtonsColor:"#FF0000",
					normalHEXButtonsColor2:"#00FF00",
					maxWidth:971,
					volume:.9,
					toolTipsButtonsHideDelay:1.5,
					toolTipsButtonsBackgroundColor:"#6a6a6a",
					toolTipsButtonFontColor:"#FFFFFF",
					//controller settings
					animateOnIntro:"yes",
					showFullScreenButton:"yes",
					showNextAndPrevButtons:"yes",
					showThumbnail:"yes",
					showLoopButton:"yes",
					showShuffleButton:"yes",
					showDownloadMp3Button:"yes",
					showBuyButton:"yes",
					showShareButton:"yes",
					showMainScrubberAndVolumeScrubberToolTipLabel:"yes",
					disableAudioScrubbar:"no",
					expandBackground:"no",
					titleColor:"#000000",
					timeColor:"#6a6a6a",
					scrubbersToolTipLabelBackgroundColor:"#6a6a6a",
					scrubbersToolTipLabelFontColor:"#FFFFFF",
					//controller align and size settings (described in detail in the documentation!)
					controllerHeight:85,
					startSpaceBetweenButtons:18,
					spaceBetweenButtons:17,
					separatorOffsetOutSpace:10,
					separatorOffsetInSpace:10,
					lastButtonsOffsetTop:14,
					allButtonsOffsetTopAndBottom:15,
					titleBarOffsetTop:12,
					mainScrubberOffsetTop:53,
					spaceBetweenMainScrubberAndTime:6,
					startTimeSpace:10,
					scrubbersOffsetWidth:3,
					scrubbersOffestTotalWidth:-6,
					volumeButtonAndScrubberOffsetTop:53,
					spaceBetweenVolumeButtonAndScrubber:5,
					volumeScrubberOffestWidth:2,
					scrubberOffsetBottom:6,
					equlizerOffsetLeft:2,
					//playlists window settings
					showPlaylistsSearchInput:"yes",
					usePlaylistsSelectBox:"yes",
					showPlaylistsSelectBoxNumbers:"yes",
					showPlaylistsButtonAndPlaylists:"yes",
					showPlaylistsByDefault:"no",
					randomizePlaylist:"no",
					playlistLoop:"yes",
					thumbnailSelectedType:"opacity",
					startAtPlaylist:0,
					startAtTrack:0,
					startAtRandomTrack:"no",
					buttonsMargins:15,
					thumbnailMaxWidth:350, 
					thumbnailMaxHeight:350,
					horizontalSpaceBetweenThumbnails:40,
					verticalSpaceBetweenThumbnails:40,
					playlistSelectorHeight: 38,
					mainSelectorBackgroundSelectedColor:"#000000",
					mainSelectorTextNormalColor:"#000000",
					mainSelectorTextSelectedColor:"#FFFFFF",
					mainButtonTextNormalColor:"#6a6a6a",
					mainButtonTextSelectedColor:"#000000",
					//playlist settings
					playTrackAfterPlaylistLoad:"no",
					showPlayListButtonAndPlaylist:"yes",
					showPlayListOnMobile:"yes",
					showPlayListByDefault:"yes",
					showPlaylistItemPlayButton:"yes",
					showPlaylistItemDownloadButton:"yes",
					showPlaylistItemBuyButton:"yes",
					forceDisableDownloadButtonForPodcast:"yes",
					forceDisableDownloadButtonForOfficialFM:"yes",
					forceDisableDownloadButtonForFolder:"yes",
					addScrollBarMouseWheelSupport:"yes",
					showTracksNumbers:"yes",
					playlistBackgroundColor:"#AAAAAA",
					trackTitleNormalColor:"#6a6a6a",
					trackTitleSelectedColor:"#000000",
					trackDurationColor:"#6a6a6a",
					playlistItemHeight: 33,
					maxPlaylistItems:100,
					nrOfVisiblePlaylistItems:10,
					trackTitleOffsetLeft:0,
					playPauseButtonOffsetLeftAndRight:11,
					durationOffsetRight:9,
					downloadButtonOffsetRight:11,
					scrollbarOffestWidth:7,
					//visualizer
					useVisualizer:'yes',
					visualizerRandomPreset:"no",
					visualizerPreset:"wave1",
					visualizerColor:["#AAAAAA", "#999999", "#888888", "#777777", "#666666"],
					visualizerCapColor: "#FFFFFF",
					//playback rate / speed
					playbackRateButtonsMargins:15,
					showPlaybackRateButton:"yes",
					defaultPlaybackRate:1, //min - 0.5 / max - 3
					playbackRateWindowTextColor:"#000000",
					//password window
					borderColor:"#CDCDCD",
					secondaryLabelsColor:"#444444",
					textColor:"#777777",
					inputBackgroundColor:"#c0c0c0",
					inputColor:"#333333",
					//search bar settings
					showSearchBar:"yes",
					showSortButtons:"yes",
					searchInputColor:"#000000",
					searchBarHeight:42,
					inputSearchTextOffsetTop:2,
					inputSearchOffsetLeft:0,
					//popup settings
					showPopupButton:"yes",
					openPopupOnPlay:"no",
					popupWindowBackgroundColor:"#6a6a6a",
					popupWindowWidth:800,
					popupWindowHeight:498,
					//a to b loop
					atbTimeTextColorNormal:"#5a5a5a",
					atbTimeTextColorSelected:"#000000",
					atbButtonTextNormalColor:"#888888",
					atbButtonTextSelectedColor:"#FFFFFF",
					atbButtonBackgroundNormalColor:"#FFFFFF",
					atbButtonBackgroundSelectedColor:"#000000",
					//login
					playIfLoggedIn:"no",
					playIfLoggedInMessage:"Please <a href='https://google.com' target='_blank'>login</a> to access this track."
				});
			}
